WHITE:
  - SKIN
SKIN:
  - PINK
PINK:
  - CORAL
CORAL:
  - FAWN
FAWN:
  - PLUM
PLUM:
  - RED
RED:
  - DARK PINK
DARK PINK:
  - MAGENTA
MAGENTA:
  - NAVY BLUE
NAVY BLUE:
  - WINE
WINE:
  - BLACK
BLACK:
  - WHITE
SKIN:
  - CORAL
PLUM:
  - DARK PINK
DARK PINK:
  - WINE
MAGENTA:
  - WINE
SKIN:
  - PEACH
PEACH:
  - DARK PINK
PEACH:
  - PLUM
PLUM:
  - GREY
GREY:
  - MAROON
MAROON:
  - WINE
BLACK:
  - SKIN
GREY:
  - DARK PINK
DARK PINK:
  - MAROON
GREY:
  - FAWN
FAWN:
  - DARK PINK
SKIN:
  - FAWN
FAWN:
  - WINE